# Generated by Django 5.2.8 on 2025-11-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_due_date_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
